apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    app: myapp
    type: frond-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-image
          image: nginx
  replicas: 6

  selector:
    matchLabels:
      type: front-end
